### PR TITLE
Initialize CUDA driver API before using it

### PR DESCRIPTION
**Pull request by Tabrizian**
Looks like there were some changes in the CUDA driver API that is affecting our GPU tensor support.

### CODE REVIEW

**Review by krishung5 — CHANGES_REQUESTED** [review]
Only need to update the copyright, otherwise LGTM!

**Comment by oandreeva-nv** [comment]
Same on copyright and I have same question as Tanmay, do we have a test to catch API changes? otherwise LGTM!

**Comment by Tabrizian** [comment]
> do we have a test to catch API changes?

We do have a test for GPU tensors but for this bug it seems like something has changed in the CuPy/CUDA side. We should call `cuInit` before using any driver API.

**Comment by krishung5** [comment]
I think we also need to change the copyright in `src/pb_tensor.cc` as well.

**Review by tanmayv25 — APPROVED** [review]

**Review by tanmayv25 — APPROVED** [review]

**Review by krishung5 — APPROVED** [review]

**Pull request merged**
