### PR TITLE
Restructure cleaning up of the futures in decoupled mode

### PR DESCRIPTION
**Pull request by Tabrizian**
Fixes https://github.com/triton-inference-server/server/issues/6270#issuecomment-1755827698

Huge shout out to @rmccorm4 for finding the root cause.

### CODE REVIEW

**Comment by rmccorm4** [comment]
Nice fix! Spoke offline, let's try to make the messages in these blocks also `unique_ptr` instead of `shared_ptr` if possible by moving the unique_ptr into the lambda captures, to reduce risk of reintroducing a leak due to long lived reference.

**Comment by Tabrizian** [comment]
@rmccorm4 I tried using unique_ptr but for some reason it looks like it needs to be a `const unique_ptr` so it looks like it might need further digging to make it work with unique_ptr.

**Review by rmccorm4 — APPROVED** [review]

**Comment by rmccorm4** [comment]
Can you add a ticket to look into it later? I think it would be good to reduce future risk.

**Review by krishung5 — APPROVED** [review]
Nice work on finding the root cause and fixing the leak!

**Comment by Tabrizian** [comment]
@rmccorm4 Filed a ticket.

**Pull request merged**
